/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthUpdatePasswordRouteImport } from './routes/auth/update-password'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedJoinRouteImport } from './routes/_authenticated/join'
import { Route as AuthenticatedExploreRouteImport } from './routes/_authenticated/explore'
import { Route as AuthenticatedCreateRouteImport } from './routes/_authenticated/create'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedTIdRouteImport } from './routes/_authenticated/t.$id'
import { Route as AuthenticatedTIdIndexRouteImport } from './routes/_authenticated/t.$id.index'
import { Route as AuthenticatedTIdRankingRouteImport } from './routes/_authenticated/t.$id.ranking'
import { Route as AuthenticatedTIdPredictionsRouteImport } from './routes/_authenticated/t.$id.predictions'
import { Route as AuthenticatedTIdMatchesRouteImport } from './routes/_authenticated/t.$id.matches'
import { Route as AuthenticatedTIdStandingsRouteImport } from './routes/_authenticated/t.$id.standings'
import { Route as AuthenticatedTIdAdminRouteImport } from './routes/_authenticated/t.$id.admin'
import { Route as AuthenticatedTIdInfoRouteImport } from './routes/_authenticated/t.$id.info'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthUpdatePasswordRoute = AuthUpdatePasswordRouteImport.update({
  id: '/update-password',
  path: '/update-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJoinRoute = AuthenticatedJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExploreRoute = AuthenticatedExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCreateRoute = AuthenticatedCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTIdRoute = AuthenticatedTIdRouteImport.update({
  id: '/t/$id',
  path: '/t/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTIdIndexRoute = AuthenticatedTIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedTIdRoute,
} as any)
const AuthenticatedTIdRankingRoute = AuthenticatedTIdRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => AuthenticatedTIdRoute,
} as any)
const AuthenticatedTIdPredictionsRoute =
  AuthenticatedTIdPredictionsRouteImport.update({
    id: '/predictions',
    path: '/predictions',
    getParentRoute: () => AuthenticatedTIdRoute,
  } as any)
const AuthenticatedTIdMatchesRoute = AuthenticatedTIdMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => AuthenticatedTIdRoute,
} as any)
const AuthenticatedTIdStandingsRoute =
  AuthenticatedTIdStandingsRouteImport.update({
    id: '/standings',
    path: '/standings',
    getParentRoute: () => AuthenticatedTIdRoute,
  } as any)
const AuthenticatedTIdAdminRoute = AuthenticatedTIdAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedTIdRoute,
} as any)
const AuthenticatedTIdInfoRoute = AuthenticatedTIdInfoRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => AuthenticatedTIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/welcome': typeof WelcomeRoute
  '/terms': typeof TermsRoute
  '/privacy': typeof PrivacyRoute
  '/home': typeof AuthenticatedHomeRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/create': typeof AuthenticatedCreateRoute
  '/explore': typeof AuthenticatedExploreRoute
  '/join': typeof AuthenticatedJoinRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/auth/': typeof AuthIndexRoute
  '/t/$id': typeof AuthenticatedTIdRouteWithChildren
  '/t/$id/admin': typeof AuthenticatedTIdAdminRoute
  '/t/$id/info': typeof AuthenticatedTIdInfoRoute
  '/t/$id/matches': typeof AuthenticatedTIdMatchesRoute
  '/t/$id/standings': typeof AuthenticatedTIdStandingsRoute
  '/t/$id/predictions': typeof AuthenticatedTIdPredictionsRoute
  '/t/$id/ranking': typeof AuthenticatedTIdRankingRoute
  '/t/$id/': typeof AuthenticatedTIdIndexRoute
}
export interface FileRoutesByTo {
  '/welcome': typeof WelcomeRoute
  '/terms': typeof TermsRoute
  '/privacy': typeof PrivacyRoute
  '/home': typeof AuthenticatedHomeRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/create': typeof AuthenticatedCreateRoute
  '/explore': typeof AuthenticatedExploreRoute
  '/join': typeof AuthenticatedJoinRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/': typeof IndexRoute
  '/auth': typeof AuthIndexRoute
  '/t/$id/admin': typeof AuthenticatedTIdAdminRoute
  '/t/$id/info': typeof AuthenticatedTIdInfoRoute
  '/t/$id/matches': typeof AuthenticatedTIdMatchesRoute
  '/t/$id/standings': typeof AuthenticatedTIdStandingsRoute
  '/t/$id/predictions': typeof AuthenticatedTIdPredictionsRoute
  '/t/$id/ranking': typeof AuthenticatedTIdRankingRoute
  '/t/$id': typeof AuthenticatedTIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/welcome': typeof WelcomeRoute
  '/terms': typeof TermsRoute
  '/privacy': typeof PrivacyRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/create': typeof AuthenticatedCreateRoute
  '/_authenticated/explore': typeof AuthenticatedExploreRoute
  '/_authenticated/join': typeof AuthenticatedJoinRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/auth/': typeof AuthIndexRoute
  '/_authenticated/t/$id': typeof AuthenticatedTIdRouteWithChildren
  '/_authenticated/t/$id/admin': typeof AuthenticatedTIdAdminRoute
  '/_authenticated/t/$id/info': typeof AuthenticatedTIdInfoRoute
  '/_authenticated/t/$id/matches': typeof AuthenticatedTIdMatchesRoute
  '/_authenticated/t/$id/standings': typeof AuthenticatedTIdStandingsRoute
  '/_authenticated/t/$id/predictions': typeof AuthenticatedTIdPredictionsRoute
  '/_authenticated/t/$id/ranking': typeof AuthenticatedTIdRankingRoute
  '/_authenticated/t/$id/': typeof AuthenticatedTIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/welcome'
    | '/terms'
    | '/privacy'
    | '/home'
    | '/auth'
    | '/admin'
    | '/create'
    | '/explore'
    | '/join'
    | '/profile'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/update-password'
    | '/auth/'
    | '/t/$id'
    | '/t/$id/admin'
    | '/t/$id/info'
    | '/t/$id/matches'
    | '/t/$id/standings'
    | '/t/$id/predictions'
    | '/t/$id/ranking'
    | '/t/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/welcome'
    | '/terms'
    | '/privacy'
    | '/home'
    | '/admin'
    | '/create'
    | '/explore'
    | '/join'
    | '/profile'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/update-password'
    | '/'
    | '/auth'
    | '/t/$id/admin'
    | '/t/$id/info'
    | '/t/$id/matches'
    | '/t/$id/standings'
    | '/t/$id/predictions'
    | '/t/$id/ranking'
    | '/t/$id'
  id:
    | '__root__'
    | '/'
    | '/welcome'
    | '/terms'
    | '/privacy'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/home'
    | '/_authenticated/admin'
    | '/_authenticated/create'
    | '/_authenticated/explore'
    | '/_authenticated/join'
    | '/_authenticated/profile'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/update-password'
    | '/auth/'
    | '/_authenticated/t/$id'
    | '/_authenticated/t/$id/admin'
    | '/_authenticated/t/$id/info'
    | '/_authenticated/t/$id/matches'
    | '/_authenticated/t/$id/standings'
    | '/_authenticated/t/$id/predictions'
    | '/_authenticated/t/$id/ranking'
    | '/_authenticated/t/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WelcomeRoute: typeof WelcomeRoute
  TermsRoute: typeof TermsRoute
  PrivacyRoute: typeof PrivacyRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/update-password': {
      id: '/auth/update-password'
      path: '/update-password'
      fullPath: '/auth/update-password'
      preLoaderRoute: typeof AuthUpdatePasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/join': {
      id: '/_authenticated/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof AuthenticatedJoinRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/explore': {
      id: '/_authenticated/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AuthenticatedExploreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/create': {
      id: '/_authenticated/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof AuthenticatedCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/t/$id': {
      id: '/_authenticated/t/$id'
      path: '/t/$id'
      fullPath: '/t/$id'
      preLoaderRoute: typeof AuthenticatedTIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/t/$id/': {
      id: '/_authenticated/t/$id/'
      path: '/'
      fullPath: '/t/$id/'
      preLoaderRoute: typeof AuthenticatedTIdIndexRouteImport
      parentRoute: typeof AuthenticatedTIdRoute
    }
    '/_authenticated/t/$id/ranking': {
      id: '/_authenticated/t/$id/ranking'
      path: '/ranking'
      fullPath: '/t/$id/ranking'
      preLoaderRoute: typeof AuthenticatedTIdRankingRouteImport
      parentRoute: typeof AuthenticatedTIdRoute
    }
    '/_authenticated/t/$id/predictions': {
      id: '/_authenticated/t/$id/predictions'
      path: '/predictions'
      fullPath: '/t/$id/predictions'
      preLoaderRoute: typeof AuthenticatedTIdPredictionsRouteImport
      parentRoute: typeof AuthenticatedTIdRoute
    }
    '/_authenticated/t/$id/matches': {
      id: '/_authenticated/t/$id/matches'
      path: '/matches'
      fullPath: '/t/$id/matches'
      preLoaderRoute: typeof AuthenticatedTIdMatchesRouteImport
      parentRoute: typeof AuthenticatedTIdRoute
    }
    '/_authenticated/t/$id/standings': {
      id: '/_authenticated/t/$id/standings'
      path: '/standings'
      fullPath: '/t/$id/standings'
      preLoaderRoute: typeof AuthenticatedTIdStandingsRouteImport
      parentRoute: typeof AuthenticatedTIdRoute
    }
    '/_authenticated/t/$id/admin': {
      id: '/_authenticated/t/$id/admin'
      path: '/admin'
      fullPath: '/t/$id/admin'
      preLoaderRoute: typeof AuthenticatedTIdAdminRouteImport
      parentRoute: typeof AuthenticatedTIdRoute
    }
    '/_authenticated/t/$id/info': {
      id: '/_authenticated/t/$id/info'
      path: '/info'
      fullPath: '/t/$id/info'
      preLoaderRoute: typeof AuthenticatedTIdInfoRouteImport
      parentRoute: typeof AuthenticatedTIdRoute
    }
  }
}

interface AuthenticatedTIdRouteChildren {
  AuthenticatedTIdAdminRoute: typeof AuthenticatedTIdAdminRoute
  AuthenticatedTIdInfoRoute: typeof AuthenticatedTIdInfoRoute
  AuthenticatedTIdMatchesRoute: typeof AuthenticatedTIdMatchesRoute
  AuthenticatedTIdStandingsRoute: typeof AuthenticatedTIdStandingsRoute
  AuthenticatedTIdPredictionsRoute: typeof AuthenticatedTIdPredictionsRoute
  AuthenticatedTIdRankingRoute: typeof AuthenticatedTIdRankingRoute
  AuthenticatedTIdIndexRoute: typeof AuthenticatedTIdIndexRoute
}

const AuthenticatedTIdRouteChildren: AuthenticatedTIdRouteChildren = {
  AuthenticatedTIdAdminRoute: AuthenticatedTIdAdminRoute,
  AuthenticatedTIdInfoRoute: AuthenticatedTIdInfoRoute,
  AuthenticatedTIdMatchesRoute: AuthenticatedTIdMatchesRoute,
  AuthenticatedTIdStandingsRoute: AuthenticatedTIdStandingsRoute,
  AuthenticatedTIdPredictionsRoute: AuthenticatedTIdPredictionsRoute,
  AuthenticatedTIdRankingRoute: AuthenticatedTIdRankingRoute,
  AuthenticatedTIdIndexRoute: AuthenticatedTIdIndexRoute,
}

const AuthenticatedTIdRouteWithChildren =
  AuthenticatedTIdRoute._addFileChildren(AuthenticatedTIdRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCreateRoute: typeof AuthenticatedCreateRoute
  AuthenticatedExploreRoute: typeof AuthenticatedExploreRoute
  AuthenticatedJoinRoute: typeof AuthenticatedJoinRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedTIdRoute: typeof AuthenticatedTIdRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCreateRoute: AuthenticatedCreateRoute,
  AuthenticatedExploreRoute: AuthenticatedExploreRoute,
  AuthenticatedJoinRoute: AuthenticatedJoinRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedTIdRoute: AuthenticatedTIdRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthUpdatePasswordRoute: typeof AuthUpdatePasswordRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthUpdatePasswordRoute: AuthUpdatePasswordRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WelcomeRoute: WelcomeRoute,
  TermsRoute: TermsRoute,
  PrivacyRoute: PrivacyRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
